//! Subsumption poset — the shared model behind time, geography and ontology hierarchies.
//!
//! A *relationship hierarchy* is a labeled partial order generated by a **covering
//! relation**. We store the covering relation as directed edges `child -> parent`: an edge
//! `(c, p)` means *c is directly subsumed by p* (`c ⊑ p`). The reflexive-transitive closure
//! of that relation is the subsumption order.
//!
//! Conventions used throughout the hierarchy module:
//!
//! - `subsumes(x, y)` == `x ⊑ y` == *y is an ancestor of x* == *x is a descendant of y*.
//! - The relation is reflexive: `subsumes(x, x)` is always true.
//! - The covering relation must be acyclic. A cycle is a data bug, not something to
//!   condense away: silently collapsing an SCC would make every roll-up over it wrong.
//!
//! Internally the poset works in **dense indices** (`u32`) rather than [`NodeId`]s. Graph
//! node ids are sparse `u64`s; the hierarchy structures (interval arrays, Fenwick trees,
//! chain tables) all want contiguous 0..n addressing. [`Poset::idx`] and [`Poset::node_at`]
//! translate at the boundary.

use std::collections::HashMap;

use crate::graph::types::{EdgeType, NodeId};
use crate::graph::GraphStore;

/// Errors raised while building or using a hierarchy.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum HierarchyError {
    /// The covering relation contains a directed cycle.
    ///
    /// Carries an example cycle, not just a count. A count tells a user their data is bad;
    /// the node ids tell them *where*, which is the difference between a dead end and a
    /// fixable import. Real ontologies do contain these — MONDO has a 14-node `is_a` cycle
    /// — and the user's next step is to file it upstream or exclude those terms, neither
    /// of which is possible without the ids.
    NotAcyclic {
        /// How many nodes could be ordered before the sort stalled.
        ordered: usize,
        /// Total nodes in the poset.
        total: usize,
        /// Every distinct cycle found, each as graph node ids `a -> b -> ... -> a`.
        /// Capped at 50 -- enough to act on, bounded for a pathological poset. Empty only
        /// if no cycle could be recovered, which should not happen when `ordered < total`.
        cycles: Vec<Vec<NodeId>>,
    },
    /// The poset is a DAG whose chain width exceeds the cap; a 2-hop index is the right
    /// substrate there. This is a *decline*, not a failure — see ADR-035.
    WidthTooHigh {
        width: usize,
        cap: usize,
        nodes: usize,
    },
    /// A NestedSet encoding was forced on a poset that is not a tree.
    NotATree,
    /// The named node is not part of this hierarchy.
    UnknownNode(NodeId),
    /// The requested index name does not exist.
    NoSuchIndex(String),
    /// An index with this name already exists.
    DuplicateIndex(String),
    /// The index is stale with respect to the graph and stale reads were not requested.
    Stale(String),
}

impl std::fmt::Display for HierarchyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            HierarchyError::NotAcyclic {
                ordered,
                total,
                cycles,
            } => {
                let unordered = total.saturating_sub(*ordered);
                write!(
                    f,
                    "covering relation has {} cycle(s): {unordered} of {total} nodes could not be ordered",
                    cycles.len()
                )?;
                for cyc in cycles.iter().take(5) {
                    let path: Vec<String> =
                        cyc.iter().map(|n| n.as_u64().to_string()).collect();
                    write!(f, "; {}", path.join(" -> "))?;
                }
                if cycles.len() > 5 {
                    write!(f, "; ... and {} more", cycles.len() - 5)?;
                }
                Ok(())
            }
            HierarchyError::WidthTooHigh { width, cap, nodes } => write!(
                f,
                "hierarchy declined: chain width {width} exceeds cap {cap} (~8·sqrt({nodes})); \
                 chain space is O(n·width) — use a 2-hop index for this poset"
            ),
            HierarchyError::NotATree => write!(f, "nested-set encoding requires a tree poset"),
            HierarchyError::UnknownNode(id) => write!(f, "node {id} is not in this hierarchy"),
            HierarchyError::NoSuchIndex(n) => write!(f, "no hierarchy index named '{n}'"),
            HierarchyError::DuplicateIndex(n) => write!(f, "hierarchy index '{n}' already exists"),
            HierarchyError::Stale(n) => write!(
                f,
                "hierarchy index '{n}' is stale; REBUILD it or opt into stale reads"
            ),
        }
    }
}

impl std::error::Error for HierarchyError {}

/// Result alias for hierarchy operations.
pub type HierarchyResult<T> = Result<T, HierarchyError>;

/// A subsumption poset over a set of graph nodes.
#[derive(Debug, Clone)]
pub struct Poset {
    /// Dense index -> graph node id.
    nodes: Vec<NodeId>,
    /// Graph node id -> dense index.
    index_of: HashMap<NodeId, u32>,
    /// `parents[i]` = dense indices directly subsuming `i`.
    parents: Vec<Vec<u32>>,
    /// `children[i]` = dense indices directly subsumed by `i`.
    children: Vec<Vec<u32>>,
    /// Topological order with every child before its parents.
    topo_up: Vec<u32>,
    /// Number of distinct covering edges.
    edge_count: usize,
}

impl Poset {
    /// Build a poset from `child -> parent` edges.
    ///
    /// `extra_nodes` lets a caller include isolated nodes that participate in the
    /// hierarchy conceptually but have no covering edge (e.g. a taxonomy root imported
    /// without a parent link). Duplicate edges are collapsed; self-loops are a cycle and
    /// are rejected.
    pub fn from_edges<I, N>(edges: I, extra_nodes: N) -> HierarchyResult<Self>
    where
        I: IntoIterator<Item = (NodeId, NodeId)>,
        N: IntoIterator<Item = NodeId>,
    {
        let mut nodes: Vec<NodeId> = Vec::new();
        let mut index_of: HashMap<NodeId, u32> = HashMap::new();
        let intern = |id: NodeId, nodes: &mut Vec<NodeId>, map: &mut HashMap<NodeId, u32>| -> u32 {
            *map.entry(id).or_insert_with(|| {
                nodes.push(id);
                (nodes.len() - 1) as u32
            })
        };

        for id in extra_nodes {
            intern(id, &mut nodes, &mut index_of);
        }

        let mut raw: Vec<(u32, u32)> = Vec::new();
        for (child, parent) in edges {
            let c = intern(child, &mut nodes, &mut index_of);
            let p = intern(parent, &mut nodes, &mut index_of);
            raw.push((c, p));
        }

        let n = nodes.len();
        let mut parents: Vec<Vec<u32>> = vec![Vec::new(); n];
        let mut children: Vec<Vec<u32>> = vec![Vec::new(); n];
        let mut seen: std::collections::HashSet<(u32, u32)> = std::collections::HashSet::new();
        let mut edge_count = 0usize;
        for (c, p) in raw {
            if !seen.insert((c, p)) {
                continue;
            }
            parents[c as usize].push(p);
            children[p as usize].push(c);
            edge_count += 1;
        }

        let topo_up = Self::topo_sort_up(&parents, &children, n, &nodes)?;
        Ok(Poset {
            nodes,
            index_of,
            parents,
            children,
            topo_up,
            edge_count,
        })
    }

    /// Build a poset from every edge in `store` whose type is one of `edge_types`.
    ///
    /// Edges are read in their stored direction: `child -[:IS_A]-> parent`. Callers that
    /// model the relation the other way round (`parent -[:HAS_CHILD]-> child`) should pass
    /// `reverse = true`.
    pub fn from_store(
        store: &GraphStore,
        edge_types: &[EdgeType],
        reverse: bool,
    ) -> HierarchyResult<Self> {
        let mut edges: Vec<(NodeId, NodeId)> = Vec::new();
        for et in edge_types {
            for edge in store.get_edges_by_type(et) {
                if reverse {
                    edges.push((edge.target, edge.source));
                } else {
                    edges.push((edge.source, edge.target));
                }
            }
        }
        Poset::from_edges(edges, std::iter::empty())
    }

    /// Kahn topological sort on `child -> parent` edges, producing children before parents.
    fn topo_sort_up(
        parents: &[Vec<u32>],
        children: &[Vec<u32>],
        n: usize,
        nodes: &[NodeId],
    ) -> HierarchyResult<Vec<u32>> {
        // in-degree counted on the *parent* side: how many children point at me.
        let mut indeg = vec![0u32; n];
        for plist in parents.iter() {
            for &p in plist {
                indeg[p as usize] += 1;
            }
        }
        let mut queue: std::collections::VecDeque<u32> =
            (0..n as u32).filter(|&i| indeg[i as usize] == 0).collect();
        let mut order = Vec::with_capacity(n);
        while let Some(u) = queue.pop_front() {
            order.push(u);
            for &p in &parents[u as usize] {
                indeg[p as usize] -= 1;
                if indeg[p as usize] == 0 {
                    queue.push_back(p);
                }
            }
        }
        if order.len() != n {
            // Every node still carrying in-degree is inside a cycle or downstream of one.
            // Walking parents from any of them must re-enter the cycle, so the first
            // repeated node closes it — that slice is a genuine cycle, not merely the
            // unordered set.
            let stalled: Vec<u32> = (0..n as u32)
                .filter(|&i| indeg[i as usize] > 0)
                .collect();

            // Recover *every* distinct cycle, not just one. A caller who has been told to
            // exclude the offending terms can only act on the ones it can see, so reporting
            // a single example costs one full reload per additional cycle (#441).
            //
            // Nodes already on a found cycle are skipped, so the walk is done once per
            // cycle rather than once per stalled node -- most stalled nodes are merely
            // downstream of a cycle, not on one.
            const MAX_CYCLES: usize = 50;
            let mut cycles: Vec<Vec<u32>> = Vec::new();
            let mut on_a_cycle: std::collections::HashSet<u32> = std::collections::HashSet::new();
            let mut seen_keys: std::collections::HashSet<Vec<u32>> = std::collections::HashSet::new();
            for &start in &stalled {
                if on_a_cycle.contains(&start) || cycles.len() >= MAX_CYCLES {
                    continue;
                }
                let cyc = Self::recover_cycle(children, &indeg, start);
                if cyc.is_empty() {
                    continue;
                }
                // Canonical key: the cycle's node set, so the same loop entered at a
                // different point is not reported twice.
                let mut key: Vec<u32> = cyc.clone();
                key.sort_unstable();
                key.dedup();
                if seen_keys.insert(key) {
                    on_a_cycle.extend(cyc.iter().copied());
                    cycles.push(cyc);
                }
            }

            return Err(HierarchyError::NotAcyclic {
                ordered: order.len(),
                total: n,
                cycles: cycles
                    .into_iter()
                    .map(|c| c.into_iter().map(|i| nodes[i as usize]).collect())
                    .collect(),
            });
        }
        Ok(order)
    }

    /// Walk **children** from `start`, staying inside the stalled set, until a node repeats.
    ///
    /// Direction matters here and is easy to get backwards. In-degree is counted on the
    /// parent side — `indeg[p]` is how many children point at `p` — so a node left with
    /// non-zero in-degree has an unprocessed *child*. Following children therefore descends
    /// toward the cycle and is guaranteed to reach it; following parents can walk away from
    /// it and dead-end, which is what happened on MONDO, where most stalled nodes are
    /// merely downstream of the cycle rather than on it.
    ///
    /// The first repeated node closes the cycle; everything before its first occurrence is
    /// the tail that led in and is dropped. The entry node is repeated at the end so the
    /// result reads as `a -> b -> a`.
    fn recover_cycle(children: &[Vec<u32>], indeg: &[u32], start: u32) -> Vec<u32> {
        let mut path: Vec<u32> = Vec::new();
        let mut seen: HashMap<u32, usize> = HashMap::new();
        let mut cur = start;
        loop {
            if let Some(&at) = seen.get(&cur) {
                let mut cycle = path[at..].to_vec();
                cycle.push(cur);
                return cycle;
            }
            seen.insert(cur, path.len());
            path.push(cur);
            // stay inside the stalled set — an ordered node cannot be on a cycle
            match children[cur as usize]
                .iter()
                .copied()
                .find(|&p| indeg[p as usize] > 0)
            {
                Some(next) => cur = next,
                None => return Vec::new(),
            }
        }
    }

    /// Number of nodes.
    pub fn n(&self) -> usize {
        self.nodes.len()
    }

    /// Number of distinct covering edges.
    pub fn m(&self) -> usize {
        self.edge_count
    }

    /// Dense index for a graph node, if it participates in the hierarchy.
    pub fn idx(&self, id: NodeId) -> Option<u32> {
        self.index_of.get(&id).copied()
    }

    /// Graph node id for a dense index.
    pub fn node_at(&self, i: u32) -> NodeId {
        self.nodes[i as usize]
    }

    /// All node ids, in dense-index order.
    pub fn node_ids(&self) -> &[NodeId] {
        &self.nodes
    }

    /// Direct parents (things that directly subsume `i`).
    pub fn parents(&self, i: u32) -> &[u32] {
        &self.parents[i as usize]
    }

    /// Direct children (things `i` directly subsumes).
    pub fn children(&self, i: u32) -> &[u32] {
        &self.children[i as usize]
    }

    /// Maximal elements — the tops of the hierarchy.
    pub fn roots(&self) -> Vec<u32> {
        (0..self.n() as u32)
            .filter(|&i| self.parents[i as usize].is_empty())
            .collect()
    }

    /// Minimal elements.
    pub fn leaves(&self) -> Vec<u32> {
        (0..self.n() as u32)
            .filter(|&i| self.children[i as usize].is_empty())
            .collect()
    }

    /// Topological order, every child before its parents.
    pub fn topo_up(&self) -> &[u32] {
        &self.topo_up
    }

    /// Topological order, every parent before its children.
    pub fn topo_down(&self) -> Vec<u32> {
        self.topo_up.iter().rev().copied().collect()
    }

    /// How many parent edges exceed one per node — the size of the exception list a
    /// near-tree encoding would have to carry.
    ///
    /// Zero exactly when the poset is a tree, so this is the continuous version of
    /// [`Self::is_tree`] and the number the probe uses to decide whether a poset is close
    /// enough to a tree to be worth treating as one.
    pub fn extra_parent_count(&self) -> usize {
        self.parents.iter().map(|p| p.len().saturating_sub(1)).sum()
    }

    /// The structural probe's first question: does every node have at most one parent?
    ///
    /// A tree (or forest) admits the nested-set encoding, which is both smaller and
    /// faster than chain decomposition, so this test is worth its single pass.
    pub fn is_tree(&self) -> bool {
        self.parents.iter().all(|p| p.len() <= 1)
    }

    /// Maximum depth from any root, for diagnostics and benchmark stratification.
    pub fn max_depth(&self) -> usize {
        let mut depth = vec![0usize; self.n()];
        let mut max = 0usize;
        for &v in self.topo_down().iter() {
            let d = self.parents[v as usize]
                .iter()
                .map(|&p| depth[p as usize] + 1)
                .max()
                .unwrap_or(0);
            depth[v as usize] = d;
            max = max.max(d);
        }
        max
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn nid(i: u64) -> NodeId {
        NodeId(i)
    }

    /// `1,2 ⊑ 0` — a two-level tree.
    fn small_tree() -> Poset {
        Poset::from_edges(vec![(nid(1), nid(0)), (nid(2), nid(0))], std::iter::empty()).unwrap()
    }

    #[test]
    fn builds_tree_and_reports_shape() {
        let p = small_tree();
        assert_eq!(p.n(), 3);
        assert_eq!(p.m(), 2);
        assert!(p.is_tree());
        assert_eq!(p.roots().len(), 1);
        assert_eq!(p.leaves().len(), 2);
        assert_eq!(p.max_depth(), 1);
    }

    #[test]
    fn duplicate_edges_are_collapsed() {
        let p = Poset::from_edges(
            vec![(nid(1), nid(0)), (nid(1), nid(0)), (nid(1), nid(0))],
            std::iter::empty(),
        )
        .unwrap();
        assert_eq!(p.m(), 1);
        assert_eq!(p.parents(p.idx(nid(1)).unwrap()).len(), 1);
    }

    #[test]
    fn extra_nodes_join_the_poset_without_edges() {
        let p = Poset::from_edges(vec![(nid(1), nid(0))], vec![nid(9)]).unwrap();
        assert_eq!(p.n(), 3);
        assert!(p.idx(nid(9)).is_some());
        // an isolated node is both a root and a leaf
        assert_eq!(p.roots().len(), 2);
    }

    #[test]
    fn diamond_is_not_a_tree() {
        // 3 ⊑ 1, 3 ⊑ 2, 1 ⊑ 0, 2 ⊑ 0
        let p = Poset::from_edges(
            vec![
                (nid(3), nid(1)),
                (nid(3), nid(2)),
                (nid(1), nid(0)),
                (nid(2), nid(0)),
            ],
            std::iter::empty(),
        )
        .unwrap();
        assert!(!p.is_tree());
        assert_eq!(p.roots().len(), 1);
        assert_eq!(p.max_depth(), 2);
    }

    #[test]
    fn cycle_is_rejected() {
        let err = Poset::from_edges(
            vec![(nid(0), nid(1)), (nid(1), nid(2)), (nid(2), nid(0))],
            std::iter::empty(),
        )
        .unwrap_err();
        assert!(matches!(err, HierarchyError::NotAcyclic { .. }));
    }

    #[test]
    fn a_cycle_error_names_the_nodes_on_the_cycle() {
        // A count tells the user their data is bad; the ids tell them where. Real
        // ontologies contain these — MONDO has a 14-node is_a cycle — and the next step
        // is to file it upstream or exclude the terms, neither possible without the ids.
        let err = Poset::from_edges(
            vec![(nid(0), nid(1)), (nid(1), nid(2)), (nid(2), nid(0))],
            std::iter::empty(),
        )
        .unwrap_err();
        let HierarchyError::NotAcyclic { cycles, .. } = &err else {
            panic!("expected NotAcyclic, got {err:?}")
        };
        let example_cycle = cycles.first().expect("at least one cycle recovered");
        // The cycle closes: first and last are the same node.
        assert!(example_cycle.len() >= 2, "got {example_cycle:?}");
        assert_eq!(
            example_cycle.first(),
            example_cycle.last(),
            "a reported cycle must close: {example_cycle:?}"
        );
        let members: std::collections::HashSet<u64> =
            example_cycle.iter().map(|n| n.as_u64()).collect();
        assert_eq!(members, [0, 1, 2].into_iter().collect(), "got {example_cycle:?}");
        // The message must name the cycle, not merely say one exists -- a caller told to
        // exclude the offending terms can only act on names it can see.
        let msg = format!("{err}");
        assert!(msg.contains("cycle"), "{msg}");
        for n in &members {
            assert!(msg.contains(&n.to_string()), "message omits node {n}: {msg}");
        }
    }

    #[test]
    fn every_distinct_cycle_is_reported_not_just_the_first() {
        // Two independent 2-cycles. Reporting only one costs the caller a full reload per
        // additional cycle, because the advice ("exclude these terms") can only be followed
        // for the terms it can see (#441).
        let err = Poset::from_edges(
            [
                (NodeId::new(0), NodeId::new(1)),
                (NodeId::new(1), NodeId::new(0)),
                (NodeId::new(2), NodeId::new(3)),
                (NodeId::new(3), NodeId::new(2)),
            ]
            .into_iter(),
            std::iter::empty(),
        )
        .unwrap_err();
        let HierarchyError::NotAcyclic { cycles, .. } = &err else {
            panic!("expected NotAcyclic, got {err:?}")
        };
        assert_eq!(cycles.len(), 2, "both cycles should be reported: {cycles:?}");

        // and each is a closed loop over its own pair, not the union of the two
        let mut sets: Vec<Vec<u64>> = cycles
            .iter()
            .map(|c| {
                let mut v: Vec<u64> = c.iter().map(|n| n.as_u64()).collect();
                v.sort_unstable();
                v.dedup();
                v
            })
            .collect();
        sets.sort();
        assert_eq!(sets, vec![vec![0, 1], vec![2, 3]], "got {sets:?}");
    }

    #[test]
    fn the_same_cycle_entered_from_two_nodes_is_reported_once() {
        // A 3-cycle has three entry points. Walking from each must not produce three
        // "distinct" cycles -- the canonical key is the node set, not the entry point.
        let err = Poset::from_edges(
            [
                (NodeId::new(0), NodeId::new(1)),
                (NodeId::new(1), NodeId::new(2)),
                (NodeId::new(2), NodeId::new(0)),
            ]
            .into_iter(),
            std::iter::empty(),
        )
        .unwrap_err();
        let HierarchyError::NotAcyclic { cycles, .. } = &err else {
            panic!("expected NotAcyclic, got {err:?}")
        };
        assert_eq!(cycles.len(), 1, "one loop, one report: {cycles:?}");
    }

    #[test]
    fn a_cycle_reached_through_a_tail_reports_only_the_cycle() {
        // 3 -> 2 is a tail leading into the 0 -> 1 -> 2 -> 0 cycle. The tail is not part of
        // the cycle and must not be reported as though it were.
        let err = Poset::from_edges(
            vec![
                (nid(0), nid(1)),
                (nid(1), nid(2)),
                (nid(2), nid(0)),
                (nid(3), nid(2)),
            ],
            std::iter::empty(),
        )
        .unwrap_err();
        let HierarchyError::NotAcyclic { cycles, .. } = &err else {
            panic!("expected NotAcyclic")
        };
        let example_cycle = cycles.first().expect("at least one cycle recovered");
        let members: std::collections::HashSet<u64> =
            example_cycle.iter().map(|n| n.as_u64()).collect();
        assert!(
            !members.contains(&3),
            "node 3 is a tail into the cycle, not on it: {example_cycle:?}"
        );
        assert_eq!(members, [0, 1, 2].into_iter().collect());
    }

    #[test]
    fn a_cycle_is_found_from_a_node_that_is_only_downstream_of_it() {
        // The MONDO shape, and the one my first fixtures were too simple to catch. Node 9
        // is a parent of 2, so it inherits 2's stall without being on the cycle itself.
        // Recovery starting there must still find 0 -> 1 -> 2, not dead-end.
        let err = Poset::from_edges(
            vec![
                (nid(0), nid(1)),
                (nid(1), nid(2)),
                (nid(2), nid(0)),
                (nid(2), nid(9)),
            ],
            std::iter::empty(),
        )
        .unwrap_err();
        let HierarchyError::NotAcyclic { cycles, .. } = &err else {
            panic!("expected NotAcyclic")
        };
        let example_cycle = cycles.first().expect("at least one cycle recovered");
        assert!(
            !example_cycle.is_empty(),
            "a cycle exists and must be recoverable from any stalled node: {err}"
        );
        assert_eq!(example_cycle.first(), example_cycle.last());
        let members: std::collections::HashSet<u64> =
            example_cycle.iter().map(|n| n.as_u64()).collect();
        assert_eq!(members, [0, 1, 2].into_iter().collect(), "got {example_cycle:?}");
        assert!(!members.contains(&9), "9 is downstream, not on the cycle");
    }

    #[test]
    fn a_two_node_cycle_is_reported() {
        let err =
            Poset::from_edges(vec![(nid(7), nid(8)), (nid(8), nid(7))], std::iter::empty())
                .unwrap_err();
        let HierarchyError::NotAcyclic { cycles, ordered, total } = &err else {
            panic!("expected NotAcyclic")
        };
        let example_cycle = cycles.first().expect("at least one cycle recovered");
        assert_eq!(*total, 2);
        assert_eq!(*ordered, 0);
        assert_eq!(example_cycle.first(), example_cycle.last());
        assert_eq!(example_cycle.len(), 3, "a -> b -> a: {example_cycle:?}");
    }

    #[test]
    fn self_loop_is_a_cycle() {
        let err = Poset::from_edges(vec![(nid(0), nid(0))], std::iter::empty()).unwrap_err();
        assert!(matches!(err, HierarchyError::NotAcyclic { .. }));
    }

    #[test]
    fn topo_up_puts_children_before_parents() {
        let p = Poset::from_edges(vec![(nid(2), nid(1)), (nid(1), nid(0))], std::iter::empty())
            .unwrap();
        let pos: HashMap<u32, usize> = p
            .topo_up()
            .iter()
            .enumerate()
            .map(|(i, &v)| (v, i))
            .collect();
        let (a, b, c) = (
            p.idx(nid(0)).unwrap(),
            p.idx(nid(1)).unwrap(),
            p.idx(nid(2)).unwrap(),
        );
        assert!(pos[&c] < pos[&b]);
        assert!(pos[&b] < pos[&a]);
        // and topo_down is the exact reverse
        assert_eq!(p.topo_down(), vec![a, b, c]);
    }

    #[test]
    fn forest_with_several_roots() {
        let p = Poset::from_edges(vec![(nid(1), nid(0)), (nid(3), nid(2))], std::iter::empty())
            .unwrap();
        assert!(p.is_tree());
        assert_eq!(p.roots().len(), 2);
    }
}
